### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by tom-s** [JustClear/colority#1]
Hi,

Great library, thanks.

https://github.com/JustClear/colority/blob/02b2bec28b03421ef4be6479f05ee5398d2bc5ba/package.json#L5

Shouldn't the "main" entry of package.json point towards "dist/colority.js" instead ?

I'm having issues when importing this plugin and bundling with Webpack because of that.

**Comment by dabanlee** [comment]
Do you have any Webpack error messages? I wouldn't have that problem.

**Comment by tom-s** [comment]
It's a cryptic message from uglify JS which is shown when it encounteers es6 code. I might be wrong but I think in order to be handled correctly by webpack (without the modules option) the main file should point to the babelified file rather than the es6 version.

**Comment by dabanlee** [comment]
Try modifying the Webpack configuration file to fix the issue.
No `Rule.exclude`:
```js
module.exports = {
    // ...
    module: {
        loaders: [{
            test: /\.js$/,
            use: ['babel-loader'],
            // exclude: /node_modules/,
        }],
    },
};
```

**Comment by tom-s** [comment]
I don't actually  want to do that, as we have a huge project and babelifying the node modules would be a big overload. I'm not ready looking for a workaround, it's just that my workmates and I thought that you didn't mean to point to the es6 file version, as libs usually point to the babelified file.
 Again, is there any reason why you point towards the es6 file in your main rather than the compiled version ?  If so could you explain me why ?

**Comment by tom-s** [comment]
Thanks !

**Comment by dabanlee** [comment]
@tom-s I have updated the `package.json`
